# Generated by Django 3.2 on 2021-05-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesharing', '0002_rename_storage_id_filemetadata_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
