# Generated by Django 3.2 on 2021-05-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0003_filemetadata_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='tags',
            field=models.ManyToManyField(related_name='file_set', to='filesharing.Tag'),
        ),
    ]
