# Generated by Django 3.2 on 2021-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0005_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='groups',
            field=models.ManyToManyField(to='filesharing.UserGroup'),
        ),
    ]
